volumes:
  media: null
  pg_data: null
  static: null

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: hikari393/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: hikari393/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - /var/www/foodgram/media/:/app/media/

  gateway:
    image: hikari393/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
      - /var/www/foodgram/media/:/app/media/
    ports:
      - 7000:80
